Repository sliit-foss/rsvp-frontend, pull requests merged in 2021-06, with the labels that each got.

#21 'Make better things' section added
  components/Layout/Container.tsx
  components/Navbar.tsx
  modules/HomePage/makeGoodThings.tsx
  pages/index.tsx
Labels: Frontend, Mobile Responsive

#34 Fixes: Use file naming conventions, Hero section responsive issue, and Remove redundant code segments
  components/Footer.tsx
  components/NextImage.tsx
  lib/logoData.ts
  modules/HomePage/HeroSection.tsx
  modules/HomePage/MakeGoodThings.tsx
  modules/HomePage/OurPartners.tsx
  modules/HomePage/WhatWeDo.tsx
  modules/HomePage/hero.tsx
  modules/HomePage/makeGoodThings.tsx
  modules/HomePage/ourPartners.tsx
  pages/index.tsx
Labels: Fixes, enhancement

#38 Feature/login
  components/Login/LoginForm.tsx
  components/Login/LoginInfo.tsx
  components/Login/LoginSignup.tsx
  package-lock.json
  pages/login.tsx
  public/login.svg
  public/logos/google_colour.svg
  public/patterns/linebreak.svg
  public/patterns/login.svg
  public/signup.svg
  tailwind.config.js
Labels: Frontend, changes requested 👀
