Repository sliit-foss/rsvp-frontend, pull requests merged in 2021-07, with the labels that each got.

#48 homepage content
  components/Footer.tsx
  modules/HomePage/HeroSection.tsx
  modules/HomePage/MakeGoodThings.tsx
  modules/HomePage/WhatWeDo.tsx
Labels: documentation

#73 Add: navbar sign in button
  components/Button.tsx
  components/ContactForm.tsx
  components/Layout/Container.tsx
  components/Layout/index.tsx
  components/Login/FormFields/SignInFormFields.tsx
  components/Login/FormFields/SignUpFormFields.tsx
  components/Login/LoginForm.tsx
  components/Navbar.tsx
  package.json
  pages/clubs.tsx
  pages/index.tsx
  public/dummypost.png
  yarn.lock
Labels: Add

#80 feature/particles.js
  components/Common/ParticleBG.tsx
  modules/HomePage/HeroSection.tsx
  modules/HomePage/MakeGoodThings.tsx
  modules/HomePage/OurPartners.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: enhancement

#86 Add: favicons and SEO config
  components/ContactForm.tsx
  components/Footer.tsx
  components/Layout/Container.tsx
  components/Layout/index.tsx
  pages/_document.jsx
  pages/clubs.tsx
  pages/contact.tsx
  pages/events/[slug].tsx
  pages/events/index.tsx
  pages/index.tsx
  pages/login.tsx
  public/favicon.png
  public/favicons/android-icon-144x144.png
  public/favicons/android-icon-192x192.png
  public/favicons/android-icon-36x36.png
  public/favicons/android-icon-48x48.png
  public/favicons/android-icon-72x72.png
  public/favicons/android-icon-96x96.png
  public/favicons/apple-icon-114x114.png
  public/favicons/apple-icon-120x120.png
  public/favicons/apple-icon-144x144.png
  public/favicons/apple-icon-152x152.png
  public/favicons/apple-icon-180x180.png
  public/favicons/apple-icon-57x57.png
  public/favicons/apple-icon-60x60.png
  public/favicons/apple-icon-72x72.png
  public/favicons/apple-icon-76x76.png
  public/favicons/apple-icon-precomposed.png
  public/favicons/apple-icon.png
  public/favicons/browserconfig.xml
  public/favicons/favicon-16x16.png
  public/favicons/favicon-32x32.png
  public/favicons/favicon-96x96.png
  public/favicons/favicon.ico
  public/favicons/manifest.json
  public/favicons/ms-icon-144x144.png
  public/favicons/ms-icon-150x150.png
  public/favicons/ms-icon-310x310.png
  public/favicons/ms-icon-70x70.png
Labels: Add

#91 update/mobile-navbar
  components/Common/ParticleBG.tsx
  components/Navbar.tsx
  modules/HomePage/MakeGoodThings.tsx
  modules/HomePage/OurPartners.tsx
  public/patterns/mobile-navbar.svg
Labels: Frontend, enhancement
